sudo: true
language: python
python:
        - "3.6" 
        - "nightly"
before_install:
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
        - mkdir geckodriver
        - tar -zxf geckodriver-v0.24.0-linux64.tar.gz  -C geckodriver
        - sudo chmod +x $PWD/geckodriver/geckodriver
        - export PATH=$PWD/geckodriver:$PATH
install: 
        - pip install -r requirements/dev.txt
script:
        - nosetests --with-coverage --cov-config .coveragerc
after_success: 
        - codecov
env:
        - MOZ_HEADLESS=1
addons: 
        - firefox: "latest"
deploy: 
        provider: heroku
        api_key: 
                secure: $(cat .heroku_api_key)
